export const keyboard: string[][] = [
  ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', 'delete'],
  ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'ñ'],
  ['z', 'x', 'c', 'v', 'b', 'n', 'm', 'enter']
]

export const words = [
  'Amor',
  'Libertad',
  'Casa',
  'Trabajo',
  'Familia',
  'Comida',
  'Felicidad',
  'Perro',
  'Gato',
  'Agua',
  'Aire',
  'Tierra',
  'Fuego',
  'Verano',
  'Invierno',
  'Otoño',
  'Primavera',
  'Sol',
  'Luna',
  'Estrella',
  'Mar',
  'Montaña',
  'Bosque',
  'Playa',
  'Río',
  'Lago',
  'Cielo',
  'Nube',
  'Arcoiris',
  'Viento',
  'Tormenta',
  'Relámpago',
  'Rayo',
  'Niebla',
  'Humo',
  'Nieve',
  'Hielo',
  'Calor',
  'Frío',
  'Alegría',
  'Tristeza',
  'Emoción',
  'Miedo',
  'Esperanza',
  'Coraje',
  'Dolor',
  'Enfermedad',
  'Salud',
  'Amistad',
  'Amigo',
  'Enemigo',
  'Fiesta',
  'Celebración',
  'Baile',
  'Música',
  'Arte',
  'Pintura',
  'Escultura',
  'Literatura',
  'Poema',
  'Historia',
  'Ciencia',
  'Tecnología',
  'Internet',
  'Redes Sociales',
  'Cine',
  'Teatro',
  'Televisión',
  'Deporte',
  'Juego',
  'Dinero',
  'Fortuna',
  'Pobreza',
  'Crimen',
  'Paz',
  'Guerra',
  'Política',
  'Democracia',
  'Libertad de Expresión',
  'Derechos Humanos',
  'Justicia',
  'Educación',
  'Trabajo en equipo',
  'Emprendimiento',
  'Viaje',
  'Aventura',
  'Espiritualidad',
  'Religión',
  'Meditación',
  'Filosofía',
  'Creatividad',
  'Innovación',
  'Aprendizaje',
  'Enseñanza',
]
